spring:
  application:
    name: arena
  datasource:
    url: "jdbc:mysql://localhost:3306/arenadb"
    username: aneo
    password: devoxx2017
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: ERROR
    fr.aneo: INFO

arena:
  startAt: 9
  endAt: 17
  inSimuMode: true # if true, schedules fights every 10 seconds, if false, apply the prod model between startAt and endAt

leaderboardUrl: "http://localhost:8081"
heroApiUrl: "http://localhost:8080"

