spring.datasource:
  url: "jdbc:mysql://localhost:3306/arenadb"
  username: aneo
  password: devoxx2017

spring.jpa:
  hibernate.ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL5Dialect

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

