/* DELETE QUIZZ TABLE'S CONTENT */
/* QUIZZ_ANSSWER AND QUIZZ_HERO_ANSWER HAVE TO BE DELETED TOO */

DELETE FROM `HERODB`.`QUIZZ_HERO_ANSWER` WHERE `QUIZZ_ID` > 0;
DELETE FROM `HERODB`.`QUIZZ_ANSWER` WHERE `ID` > 0;
DELETE FROM `HERODB`.`QUIZZ` WHERE `ID` > 0;

