INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(1,"En Java, comment indiquer qu'une classe A hérite d'une classe B ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(2,"En Java, la liaison tardive est essentielle pour assurer", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(3,"Java est un langage développé par", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(4,"En Java, Lesquelles de ces affirmations sont vraies sur les constructeurs?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(5,"JAXB est l'acronyme de ", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(6,"En Java, quelle librairie permet (entre autre) de ne pas écrire les Getter/Setter d'une classe ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(7,"Une classe déclarée finale ne doit avoir aucune méthode abstraite.", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(8,"Qu’est-ce qui est faux pour les interfaces ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(9,"Une classe déclarée finale ne peut être étendue.", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(10,"Laquelle de ces plateformes est utilisée pour des applications clientes (ou front-office) ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(11,"Quel type de flux est l'objet System. out ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(12,"Java supporte l'héritage multiple", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(13,"Quel objet nous donne des informations sur la requête SQL exécutée ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(14,"Quel est le type renvoyé par la méthode Math. random()  ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(15,"Pourquoi le framwork Spring est-il qualifié comme un conteneur léger ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(16,"Lequel des interfaces suivantes du package Java. util réalise l'implémentation de Java. util. Hashtable ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(17,"Que peut gérer Maven ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(18,"Avec Hibernate, pour qu'un attribut soit instancié avec un bean on doit utiliser l'annotation ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(19,"Quelle classe n’a pas de classe mère ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(20,"Le polymorphisme sert à  ", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(21,"Quelle édition java est destinée au développement d'applications pour ordinateurs personnels ou des applets ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(22,"Lequel est un exemple de polymorphisme ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(23,"Le mot clé protected associé à une variable ou méthode  :", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(24,"L’interprétation des programmes Java est effectuée par", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(25,"Quel mot clé est utilisé pour annuler complètement l'exécution d'une boucle ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(26,"Lequel n'est pas un serveur d'application dans un environement JEE ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(27,"Quel est le fichier de configuration de Hibernate ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(28,"Quelle librairie AngularJS utilise-t'il pour manipuler les éléments DOM HTML ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(29,"Quel service AngularJS permet d'utiliser les promises ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(30,"Quelle est la solution proposée par AngularJS qui permet aux développeurs d'enrichir les balises HTML avec de la génération de template HTML et/ou de la gestion d'événement javascript ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(31,"Quel framework peut-être utilisé avec le langage OZ", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(32,"En C, le symbole pour déférencer une variable est", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(33,"Lequel de ces conteneur n'existe pas dans la librairie standar C++", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(34,"Les développeurs qui commit du code commenté ont", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(35,"En 1971 apparaît le premier microprocesseur, lequel était ce ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(36,"GNU est l'acronyme de", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(37,"HADOPI est ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(38,"Le premier programme assembleur a été écrit par Nathaniel Rochester pour l'IBM 701", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(39,"Qui sont les fondateurs de Google ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(40,"En quelle année a été créé ANEO ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(41,"Quel stand occupe ANEO à la devoxx ?", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(42,"ANEO est une entreprise", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(43,"Le siège d'ANEO se situe près ", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(44,"ANEO est l'acronyme de", TRUE, FALSE);
INSERT INTO `herodb`.`QUIZZ`(`ID`,`QUESTION`,`ACTIVE`,`IS_BONUS`) VALUES(45,"Le socle Master Data Management d'ANEO gère le logiciel référenciel", TRUE, FALSE);
