aneo.security.jwt:
  expirationTime: 86400000 # 1 day = 1000 * 60 * 60 * 24 ms
  issuer: aneo
  secretKey: xm8EV6Hy5RAFK4EEACIDAwQus

spring.datasource:
  url: "jdbc:mysql://localhost/herodb"
  username: aneo
  password: devoxx2017

spring.jpa:
  hibernate.ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL5Dialect

liquibase:
  change-log: classpath:/changelog/db.changelog-master.yaml
