-- MySQL Script generated by MySQL Workbench
-- 03/09/17 23:41:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema devoxx-lejeu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `devoxx-lejeu` ;

-- -----------------------------------------------------
-- Schema devoxx-lejeu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devoxx-lejeu` DEFAULT CHARACTER SET utf8 ;
USE `devoxx-lejeu` ;

-- -----------------------------------------------------
-- Table `devoxx-lejeu`.`Avatar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devoxx-lejeu`.`Avatar` ;

CREATE TABLE IF NOT EXISTS `devoxx-lejeu`.`Avatar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mimeType` VARCHAR(45) NULL,
  `depiction` BIT(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devoxx-lejeu`.`HeroStat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devoxx-lejeu`.`HeroStat` ;

CREATE TABLE IF NOT EXISTS `devoxx-lejeu`.`HeroStat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attackLevel` INT NULL DEFAULT 5,
  `currentBonnus` INT NULL,
  `wins` INT NULL DEFAULT 0,
  `losses` INT NULL,
  `currentRanking` INT NULL DEFAULT 0,
  `bestRanking` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devoxx-lejeu`.`Hero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devoxx-lejeu`.`Hero` ;

CREATE TABLE IF NOT EXISTS `devoxx-lejeu`.`Hero` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `role` INT NULL,
  `avatar` INT NULL,
  `heroStats` INT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `heroStats_idx` (`heroStats` ASC),
  INDEX `avatar_idx` (`avatar` ASC),
  CONSTRAINT `avatar`
    FOREIGN KEY (`avatar`)
    REFERENCES `devoxx-lejeu`.`Avatar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `heroStats`
    FOREIGN KEY (`heroStats`)
    REFERENCES `devoxx-lejeu`.`HeroStat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devoxx-lejeu`.`Quizz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devoxx-lejeu`.`Quizz` ;

CREATE TABLE IF NOT EXISTS `devoxx-lejeu`.`Quizz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NULL,
  `answerAsString` VARCHAR(45) NULL,
  `userChoice` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO aneo@'localhost';
 DROP USER aneo@'localhost';
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'aneo'@'localhost' IDENTIFIED BY 'devoxx2017';

GRANT SELECT ON TABLE `devoxx-lejeu`.* TO 'aneo'@'localhost';
GRANT SELECT, INSERT, TRIGGER, ALTER ON TABLE `devoxx-lejeu`.* TO 'aneo'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
